import {StyleSheet} from 'react-native';
export const GlobalStyles = StyleSheet.create({
  containers: {
    flex: 1,
    backgroundColor: '#F1F1F1',
    marginTop: 10,
    marginHorizontal: 20,
  },
  input: {
    marginBottom: 10,
    backgroundColor: 'white',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 15,
  },
  dateInput: {
    marginBottom: 10,
    backgroundColor: 'white',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 16,
    fontSize: 15,
  },
  dateInput2: {
    marginBottom: 10,
    backgroundColor: 'white',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 16,
    fontSize: 15,
    justifyContent: 'center',
    alignContent: 'center',
  },
  font20: {
    fontSize: 20,
  },
  label: {
    fontSize: 20,
    marginBottom: 10,
  },
  label2: {
    fontSize: 20,
    marginBottom: 10,
    flex: 5,
  },
  subLabel: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  picker: {
    borderWidth: 1,
    borderColor: 'black',
    borderStyle: 'solid',
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 10,
  },
  radio: {
    justifyContent: 'space-around',
    alignItems: 'flex-end',
  },
  radio2: {
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  flexDirRow: {
    flexDirection: 'row',
  },
  font22: {
    fontSize: 22,
  },
  roundButton1: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
    borderRadius: 20,
    backgroundColor: '#289EF4',
    marginHorizontal: 50,
    marginVertical: 20,
  },
  roundButtonAdd: {
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    padding: 10,
    borderRadius: 100,
    backgroundColor: '#289EF4',
    marginVertical: 15,
  },
  roundButtonCancel: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  colorWhite: {
    color: 'white',
  },
  colorCrimson: {
    color: 'crimson',
  },
  flex1: {
    flex: 1,
  },
  MR10: {
    marginRight: 40,
  },
  font15: {
    fontSize: 15,
  },
  items: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 24,
    backgroundColor: 'white',
    borderColor: 'black',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 20,
  },
  item_text: {
    paddingHorizontal: 10,
    paddingVertical: 20,
    color: 'black',
    fontSize: 22,
    fontWeight: 'bold',
    flex: 2,
  },
  item_details: {
    paddingHorizontal: 10,
    paddingVertical: 20,
    flex: 4,
  },
  item_name: {
    fontSize: 22,
    color: 'black',
    fontWeight: 'bold',
  },
  icon: {
    alignSelf: 'center',
    padding: 20,
  },
  status_approved: {
    textAlign: 'center',
    alignSelf: 'center',
    padding: 15,
    color: 'white',
    backgroundColor: '#52FF00',
    flex: 1,
    marginRight: 10,
    borderRadius: 20,
  },
  status_reject: {
    textAlign: 'center',
    alignSelf: 'center',
    padding: 15,
    color: 'white',
    backgroundColor: 'red',
    flex: 1,
    marginRight: 10,
    borderRadius: 20,
  },
  status_pending: {
    textAlign: 'center',
    alignSelf: 'center',
    padding: 15,
    color: 'white',
    backgroundColor: '#FF6400',
    flex: 1,
    marginRight: 10,
    borderRadius: 20,
  },
  backgroundRed: {
    backgroundColor: 'red',
  },
  MT15: {
    marginTop: 15,
  },
});
